//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksInWPF4.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFTasks4")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyFirstService")]
    public interface IMyFirstService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetData", ReplyAction="http://tempuri.org/IMyFirstService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyFirstService/GetData", ReplyAction="http://tempuri.org/IMyFirstService/GetDataResponse")]
        System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
        
        string EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyFirstService/GetDataUsingDataContractResponse")]
        TasksInWPF4.ServiceReference1.CompositeType GetDataUsingDataContract(TasksInWPF4.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyFirstService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyFirstService/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(TasksInWPF4.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        TasksInWPF4.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetNames", ReplyAction="http://tempuri.org/IMyFirstService/GetNamesResponse")]
        System.Collections.Generic.List<string> GetNames();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyFirstService/GetNames", ReplyAction="http://tempuri.org/IMyFirstService/GetNamesResponse")]
        System.IAsyncResult BeginGetNames(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetNames(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetNumbers", ReplyAction="http://tempuri.org/IMyFirstService/GetNumbersResponse")]
        System.Collections.Generic.List<int> GetNumbers();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyFirstService/GetNumbers", ReplyAction="http://tempuri.org/IMyFirstService/GetNumbersResponse")]
        System.IAsyncResult BeginGetNumbers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<int> EndGetNumbers(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyFirstServiceChannel : TasksInWPF4.ServiceReference1.IMyFirstService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TasksInWPF4.ServiceReference1.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TasksInWPF4.ServiceReference1.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyFirstServiceClient : System.ServiceModel.ClientBase<TasksInWPF4.ServiceReference1.IMyFirstService>, TasksInWPF4.ServiceReference1.IMyFirstService {
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
        
        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNamesDelegate;
        
        private EndOperationDelegate onEndGetNamesDelegate;
        
        private System.Threading.SendOrPostCallback onGetNamesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNumbersDelegate;
        
        private EndOperationDelegate onEndGetNumbersDelegate;
        
        private System.Threading.SendOrPostCallback onGetNumbersCompletedDelegate;
        
        public MyFirstServiceClient() {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFirstServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
        
        public event System.EventHandler<GetNamesCompletedEventArgs> GetNamesCompleted;
        
        public event System.EventHandler<GetNumbersCompletedEventArgs> GetNumbersCompleted;
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int value = ((int)(inValues[0]));
            return this.BeginGetData(value, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            string retVal = this.EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        public void GetDataAsync(int value, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        public TasksInWPF4.ServiceReference1.CompositeType GetDataUsingDataContract(TasksInWPF4.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDataUsingDataContract(TasksInWPF4.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TasksInWPF4.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result) {
            return base.Channel.EndGetDataUsingDataContract(result);
        }
        
        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TasksInWPF4.ServiceReference1.CompositeType composite = ((TasksInWPF4.ServiceReference1.CompositeType)(inValues[0]));
            return this.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result) {
            TasksInWPF4.ServiceReference1.CompositeType retVal = this.EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataUsingDataContractCompleted(object state) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataUsingDataContractAsync(TasksInWPF4.ServiceReference1.CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        public void GetDataUsingDataContractAsync(TasksInWPF4.ServiceReference1.CompositeType composite, object userState) {
            if ((this.onBeginGetDataUsingDataContractDelegate == null)) {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null)) {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null)) {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<string> GetNames() {
            return base.Channel.GetNames();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNames(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNames(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<string> EndGetNames(System.IAsyncResult result) {
            return base.Channel.EndGetNames(result);
        }
        
        private System.IAsyncResult OnBeginGetNames(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetNames(callback, asyncState);
        }
        
        private object[] OnEndGetNames(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = this.EndGetNames(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNamesCompleted(object state) {
            if ((this.GetNamesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNamesCompleted(this, new GetNamesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNamesAsync() {
            this.GetNamesAsync(null);
        }
        
        public void GetNamesAsync(object userState) {
            if ((this.onBeginGetNamesDelegate == null)) {
                this.onBeginGetNamesDelegate = new BeginOperationDelegate(this.OnBeginGetNames);
            }
            if ((this.onEndGetNamesDelegate == null)) {
                this.onEndGetNamesDelegate = new EndOperationDelegate(this.OnEndGetNames);
            }
            if ((this.onGetNamesCompletedDelegate == null)) {
                this.onGetNamesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNamesCompleted);
            }
            base.InvokeAsync(this.onBeginGetNamesDelegate, null, this.onEndGetNamesDelegate, this.onGetNamesCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<int> GetNumbers() {
            return base.Channel.GetNumbers();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNumbers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNumbers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<int> EndGetNumbers(System.IAsyncResult result) {
            return base.Channel.EndGetNumbers(result);
        }
        
        private System.IAsyncResult OnBeginGetNumbers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetNumbers(callback, asyncState);
        }
        
        private object[] OnEndGetNumbers(System.IAsyncResult result) {
            System.Collections.Generic.List<int> retVal = this.EndGetNumbers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNumbersCompleted(object state) {
            if ((this.GetNumbersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNumbersCompleted(this, new GetNumbersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNumbersAsync() {
            this.GetNumbersAsync(null);
        }
        
        public void GetNumbersAsync(object userState) {
            if ((this.onBeginGetNumbersDelegate == null)) {
                this.onBeginGetNumbersDelegate = new BeginOperationDelegate(this.OnBeginGetNumbers);
            }
            if ((this.onEndGetNumbersDelegate == null)) {
                this.onEndGetNumbersDelegate = new EndOperationDelegate(this.OnEndGetNumbers);
            }
            if ((this.onGetNumbersCompletedDelegate == null)) {
                this.onGetNumbersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNumbersCompleted);
            }
            base.InvokeAsync(this.onBeginGetNumbersDelegate, null, this.onEndGetNumbersDelegate, this.onGetNumbersCompletedDelegate, userState);
        }
    }
}
